# NumPy Problems

____________

#### Import NumPy as np

In [ ]:
import numpy as np
# I have imported numpy and named it np.

#### Create an array of 20 zeros 

In [ ]:
np.zeros(20)
# I made a list of 20 zeros into an array.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)
# I made an array out of a list of ten ones.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
np.ones(10)*5
# i made an array out of a list of ten ones and multiplied all the values by five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,50)
# I made an array of integers with a range of 10 to 50.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,50,2)
# I made an array of integers divisible by 2 with a range of 10 to 50.

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix=np.arange(0,9)
#formed an array with values ranging from 0 to 8
matrix.reshape(3,3)
# reformatted the matrix into three lists, each with three values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)
#I made a matrix with three lists of three values each, with the main diagonal value.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)
# I made an array with a random integer between 0 and 1 in it.

array([0.46075915])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.rand(25)
#I made a 25-number array with values ranging from 0 to 1.

array([0.86056248, 0.95048926, 0.7900092 , 0.10927217, 0.34624687,
       0.61987215, 0.30175343, 0.60959534, 0.22820033, 0.04407233,
       0.38147661, 0.77358447, 0.71381538, 0.03122349, 0.93035857,
       0.5793032 , 0.56853106, 0.09667901, 0.46534025, 0.96708326,
       0.79014485, 0.84370532, 0.10104615, 0.53669044, 0.1491551 ])

#### Create the following matrix:

In [ ]:
np.arange(0.01,1.01,.01).reshape(10,10)
# I made a matrix with increments of.01 between 0.01 and 1.01
# I reformatted the matrix into ten lists of ten values each.

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.random.rand(20)
# I made a 20-number array with values ranging from 0 to 1.

array([0.40611429, 0.27250295, 0.12887041, 0.16274263, 0.45454386,
       0.518632  , 0.35001467, 0.71005581, 0.57849695, 0.19511575,
       0.68438021, 0.94350101, 0.90227524, 0.83447059, 0.19766466,
       0.74429456, 0.06285816, 0.4796037 , 0.86895128, 0.69695985])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat
# formed an array with values ranging from 1 to 26
# converted the array to five lists, each with five values.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2][3]
#Only the 3 value from the second row was chosen.   

14

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3][4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[0:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
 mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Cheers!